use_frameworks!

platform :ios, '8.0'

target 'FFCategoryDemo_Example' do
  pod 'FFCategoryDemo', :path => '../'
  pod 'MBProgressHUD'
  pod 'AFNetworking'
  pod 'FMDB'
  
  target 'FFCategoryDemo_Tests' do
    inherit! :search_paths

    
  end
end
